### ISSUE TITLE
UI issues on Flight Screen

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/Tower#489]
From @jason4short
![pastedgraphic-8](https://f.cloud.github.com/assets/3289118/1790100/5cad9c6c-696c-11e3-98ce-594ec67cde44.png)
- [x] Home doesn't work 
- [x] Missing home icon
- [x] Bar has incorrect visual
- [x] Flight time dorsn't work
- [x] Mode spinner must be wider
- [x] On connection incorrectly reports as Drift mode
- [x] Altimeter widget is not work - #451
- [x] Dimmed text on the altitude display should show the  target altitude - #451
- [ ] Need to add state to action buttons - #500 
- [x] WP are not editable
- [x] WP not in sync with edit screen
- [x] Goto my location button doesn't work
- [ ] Missing text data on drone marker
- [x] Drag anywhere on modeDetail fragment - #473
