### ISSUE TITLE
Release of v2

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/Tower#660]
The following issues must be solved so we can do the official release (either by solving them, or omitting the feature):
### General issues:
- [x] I had a RC failsafe warning when it never really happened  (will be removed for the release, moved to #677)
- [x] It says "connected" everytime I click on anything. Can that be stopped? (fixed at #674)
- [x] The mode button should only be updated by the drone, clicking it should only send a command. Currently clicking it sends the command and updates the button. (moved to #675)
- [x] When I change a parameter I can't save it. Isn't the title bar supposed to change? (I'm not sure what's the problem here, I just tried writing, reading, editing a parameter without problem. I did #678 to fix a problem with the toast message. If the UI needs an update we can do it at a further release).
  ![2014-02-28](https://f.cloud.github.com/assets/3289118/2298965/e6f045c0-a0c4-11e3-8aee-2d25a9712a92.png)
### Editor issues:
- [x] Distance still says 200m, Flight time 3:30s (will be removed for the release, moved to #676)
- [x] Draw a mission, Lift finger, then draw a second leg of the mission. The Paintbrush icon is still active, but the draw mode is no longer active. (#670)
- [x] If you press +WP, then tap any other WP, the side panel will pop out. To hide it you tap the map, but the +WP is still active and you misplace a WP.  (#670)
- [x] Tap the +WP icon, then tap a mission item in the bottom tray. The +WP icon should deactivate. (#670)
- [x] Select trash, long press on WP in list, hit delete in action bar, trash is shown selected, but mode is not active. (#670)
- [x] Long press on a mission item in the tray should deselect the current tool (#670)
