### ISSUE TITLE
Release 2.3.1

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/Tower#755]
Here are a couple of issues that need to be solved before the beta release of 2.3.1.
_Items that need fixing_:
- [x] Delay is too high #730  
- [x] Land item should default to zero #752 
- [x] tts should speak auto mission progress #753

_Possible fixes_ 
- [ ] Mode selection Mask #718 
- [ ] Auto Mission Progress #754 

_Just for the release:_
- [x] RTL should not be present for the user
- [x] ROI should also be removed

Latest Release Candidate is:
https://github.com/DroidPlanner/droidplanner/releases/tag/Droidplanner_v2.3.1_RC1
